export const GET_BASE_ROUTE_START = 'GET_BASE_ROUTE_START';
export const RESET_BASE_ROUTE = 'RESET_BASE_ROUTE';
export const GET_BASE_ROUTE_SUCCESS = 'GET_BASE_ROUTE_SUCCESS';
export const GET_BASE_ROUTE_FAILURE = 'GET_BASE_ROUTE_FAILURE';
export const UPDATE_BASE_ROUTE = 'UPDATE_BASE_ROUTE';
